concord-consortium/vortex

- __mocks__/react-jsonschema-form.tsx
- package.json
- src/shared/components/experiment.test.tsx
- src/shared/components/experiment.tsx
- src/shared/components/section.test.tsx
- src/shared/components/section.tsx
[#170896583]
`Experiment` component can be treated both as an uncontrolled or controlled "input", so it's up to the wrapping component how it's being used. Data is saved on every change, there's no submit button and no validation (as that's what Leslie wanted for now, as the workflow is not clear if we try to validate the data).
> Handle form state saving and notifying parents about changes + tests

- package-lock.json
- package.json
- src/data/experiments.json
- src/mobile-app/components/experiment-picker.tsx
- src/mobile-app/hooks/use-experiments.test.ts
- src/mobile-app/hooks/use-experiments.ts
- src/setupTests.js
- src/setupTests.ts
- src/shared/components/experiment.test.tsx
- src/shared/experiment-types.ts
- src/shared/index.tsx
- src/shared/test/running-tests.ts
- src/shared/utils/log.ts
- Adds version field to experiment data
- Adds check for version number and placeholder for migrations
- Adds boolean return value to note is an app upgrade is required
- Moves experiment metadata into its own subobject
- Adds a logging facility with log levels
- Changes test setup to use TypeScript to allow log level to be set in tests
- Removes runningTests test helper function
> Added versioning to experiment data [#170908848]

- src/data/experiments.json
- src/mobile-app/components/app.tsx
- src/mobile-app/components/experiment-wrapper.module.scss
- src/mobile-app/components/experiment-wrapper.tsx
- src/mobile-app/components/run-picker.module.scss
- src/mobile-app/components/run-picker.tsx
- src/mobile-app/hooks/use-runs.test.tsx
- src/mobile-app/hooks/use-runs.ts
- src/shared/components/experiment.module.scss
- src/shared/components/experiment.tsx
- src/shared/components/initials.module.scss
- src/shared/components/initials.tsx
- src/shared/components/metadata.module.scss
- src/shared/components/metadata.tsx
- src/shared/components/section.test.tsx
- src/shared/components/section.tsx
- src/shared/experiment-types.ts
- src/shared/utils/format-time.ts
1. Add section components (`Metadata` component) + specify types for future section components.
2. Display selected form field as experiment title (`titleField` in experiment schema).
3. Refactor use-runs, move more functionality there + update specs.
4. Style experiment header.
5. Style runs picker.
BTW, I'm wondering if we need `experiment.schema` field? I guess we could move schema fields one level higher to have fewer nested objects and avoid decision making where to put a new field (top-level experiment or schema). :wink:
> Add section components (e.g. metadata), display selected form field as experiment title + misc changes

- package-lock.json
- src/data/experiments.json
- src/mobile-app/components/experiment-wrapper.tsx
- src/mobile-app/hooks/use-runs.ts
- src/mobile-app/hooks/use-sensor.ts
- src/sensors/sensor.ts
- src/shared/components/bootstrap-vortex-theme.scss
- src/shared/components/data-table-field.module.scss
- src/shared/components/data-table-field.tsx
- src/shared/components/experiment.tsx
- src/shared/components/field-template.module.scss
- src/shared/components/field-template.tsx
- src/shared/components/form.tsx
- src/shared/components/icon.tsx
- src/shared/components/metadata.module.scss
- src/shared/components/section.module.scss
- src/shared/components/section.test.tsx
- src/shared/components/section.tsx
- src/shared/components/variables.scss
- src/shared/experiment-types.ts
- src/shared/index.html
- src/shared/index.tsx
- src/shared/utils/format-time.ts
- src/shared/utils/get-url-param.ts
Some UI elements (average) and tests are missing, but I guess there's enough progress to take a look and check if the direction is right.
@scytacki, I've changed the data table schema. Instead of the object of arrays, now we have an array of objects. That turned out to be easier to work with. Also, if we don't use our custom dataTable component, UI provided by React JSONSchema Form is very similar to what you proposed as a simplified view.
LARA app will be able to disable sensor support using `experimentConfig` that has been just added to the `Experiment` component.
`?mockSensor` URL param can be used to use MockedSensor for a demo or test purposes.
Demo: 
https://models-resources.concord.org/vortex/branch/data-table/mobile-app/index.html
Demo with Mocked Sensor: …
> Add data table

- src/shared/utils/delay-promise.test.ts
- src/shared/utils/serialize-promises.test.ts
Before this change we would get random test failures because the time measurment was off by 1ms.
> Changed exact test time measurements to be within 10% tolerance

- src/cordova-wrapper/config.xml
- src/cordova-wrapper/package-lock.json
- src/cordova-wrapper/package.json
This PR includes a couple of small changes required to get the app on TestFlight without errors or warnings, [#171332364]. I branched off the dev branch, so until that PR is merged this one is a little bloated. All the changes here are in commit f9c66b5
Also needed the following settings added to the generated Vortex-info.plist, I wasn't able to get this information to populate the plist file automatically from other sources:
<key>NSPhotoLibraryUsageDescription</key>
<string>Camera access is required to photograph data collection sites and also to scan a QR code to upload data back to the classroom activity.</string>
<key>NSBluetoothPeripheralUsageDescription</key>
<string>This application uses bluetooth to find, connect and transfer data from Sensor Tag bluetooth devices</string>
Also …
> iOS TestFlight additions

- src/sensors/devices/sensor-tag-cc2650.ts
Some version of the CC2650 don't have an IR sensor
so they wouldn't have an ambient temperature on the IR sensor.
We could merge the CC1350 and the CC2650 into one, but it might be useful to
keep them separate to support other differences in the future.
> Use the humidity sensors ambient temperature

- src/mobile-app/components/sensor.tsx
- src/sensors/device-sensor.ts
This fixes three issues:
1. It clears the error message before connecting so that the "Connecting..." message shows if there was an existing error (such as timing out before connecting)
2. It removes the immediate BLE disconnect and instead uses the existing codepath to perform the disconnect after the final poll is done to get the values.
3. It performs the disconnect without checking for an existing connection to ensure we are disconnected.
> Fix sensor disconnect/re-connect [#171524472]

- src/cordova-wrapper/package-lock.json
- src/cordova-wrapper/package.json
- src/mobile-app/components/app.tsx
- src/shared/components/data-table-field.tsx
- src/shared/components/photo-or-note-field.tsx
- src/shared/utils/dialogs.ts
- tslint.json
To avoid renaming the iOS app the Cordova dialog plugin is used to set the title.  This does cause some extra code changes as that plugin uses callbacks instead of blocking and returning true/false on confirm.
> Change alert/confirm titles to "Data Collector" [#171550615]

- src/cordova-app/index.html
- src/data/experiments.json
Set the Cordova app index.html to use UTF-8 and added degree symbol back to Schoolyard Investigation.
> Fixed unicode encoding issue with degree symbol [#171607986]

- src/shared/components/menu.tsx
Adds a global click handler that closes the menu if it is showing.
> Fixed closing menu if clicked outside of menu [#171607882]

- src/shared/components/data-table-field.module.scss
- src/shared/components/data-table-field.test.tsx
- src/shared/components/data-table-field.tsx
- src/shared/index.html
- src/shared/index.sass
- src/shared/index.tsx
Adds the dropdown JSON Schema definition to tables.
This change is visible in example 3 in shared/index.html.  I also updated the shared/index.html file to make the schema json collapsible with the default being collapsed to reduce the amount of scrolling needed to test the various shared examples.
> Add dropdown datatype [#171289767]

- src/shared/components/photo-or-note-field.tsx
This ensures that uploads change the notes/photos field if they are focused when the upload happens.
Currently, because of a UI change, it isn't possible to upload while in the notes field but it may be possible in the future.
> Added listen for prop changes to notes/photos [#171084232]

- README.md
- src/mobile-app/components/sensor-strength.module.scss
- src/mobile-app/components/sensor-strength.test.ts
- src/mobile-app/components/sensor-strength.tsx
- src/mobile-app/components/sensor.module.scss
- src/mobile-app/components/sensor.tsx
- src/sensors/bluetooth.d.ts
- src/sensors/device-sensor.ts
- src/sensors/mock-sensor.ts
- src/sensors/sensor.ts
- src/shared/components/data-table-field.tsx
- src/shared/index.html
Also fixes sensor disconnecting when entering edit mode and auto-reconnecting after connect -> disconnect -> connect.  Previously the sensor component was not rendered when entering edit mode which caused all its state to be lost.  Now it is always rendered and the menus option to enter/leave edit mode is pushed down into the sensor component.
> Add sensor picker ui [#171332391]

- src/lara-app/components/app.tsx
S3 Vortex authoring isn't ready for prime-time yet.
This commit reverts the LARA authoring interface to select an internal experiment.
[#213530316]
https://www.pivotaltracker.com/n/projects/736901/stories/171096164/comments/213530316
> Revert LARA template authoring dropdown

- cypress/integration/branch/experiment.setup.spec.js
- cypress/supports/elements/ExperimentSetup.js
- src/data/experiments.json
- src/mobile-app/components/experiment-wrapper.module.scss
- src/mobile-app/components/experiment-wrapper.tsx
Remove the Label field from the form by editing` src/data/experiments.json`, update tests accordingly.
The change diff for the Cypress tests is larger because of formatting fixes. The main addition was `cypress/integration/branch/experiment.setup.spec.js` lines 44-51 for testing the changes to the name of the experiment, and removing calls to `getLabelTextBox()`
> 172560741 adjust metadata

- src/data/experiments.json
- src/mobile-app/components/experiment-wrapper.module.scss
- src/mobile-app/components/experiment-wrapper.tsx
- src/mobile-app/components/sensor.tsx
- src/shared/components/menu.tsx
- src/shared/components/photo-or-note-field.module.scss
- src/shared/components/photo-or-note-field.tsx
Update the UI in response to feedback to include the following:
- Menu icons adjusted to show the Delete icon on the photos page to delete a photo. I left the functionality as-is, so the menu will show you a "delete" option when you click it (a useful "are you sure")
- Menu icons added for Save, Upload, and Rename on Experiment header
- Added rename for Experiment via a form field instead of in the header
- Changed camera functionality to show the picture you just took for 2s then return to taking more pictures. I left the thumbnails on screen to give the user the option of viewing their photos.
- Notes and Photos order of tabs flipped
- Sensor icon, when disconnected, can be tapped to connect, instead of using the menu
- Added missing icon for Connect menu option
> UI Cleanup [#172609679]

- README.md
- src/cordova-wrapper/clean.sh
- src/cordova-wrapper/package.json
I made a simple script that gives a reliable way to clean out the old code from Cordova installations. It made it much easier to test out new versions of the bluetooth plugin, and it preserves my xcode settings, so no more copy-paste by hand.
> Fixing the sticky Cordova plugins

- package-lock.json
- package.json
- src/lara-app/components/app.tsx
- src/lara-app/components/runtime.tsx
- src/lara-app/hooks/interactive-api.ts
- src/shared/utils/log.ts
@scytacki, an implementation generally follows the second idea from this doc:
https://docs.google.com/document/d/1V5rA7HBERnlw1IfOo5XAB7aser5bngVCP9uUSbKfC4Y/edit
`classInfoUrl` and `interactiveStateUrl` are not used anymore. Vortex would just try to `getFirestoreJWT`. When it fails, it'll automatically switch to preview mode.
`runKey` is read from the interactive state in runtime now, so users that worked with Vortex before shouldn't lose their data. If there's no `runKey` in the interactive state, it'll be automatically generated.
ActivityPlayer was not polling interactive state, so now Vortex will automatically send it itself, right after `runKey` is generated. This ensures that user can continue his works.
`previewMode` is now exported explicitly. We no longer assume that `!runKey` …
> Make Vortex working in ActivityPlayer

- src/lara-app/components/app.tsx
- src/lara-app/components/runtime.tsx
- src/lara-app/hooks/interactive-api.ts
[#175739194]
Data is saved in the linked interactive state. That way, graph interactive can start observing Votex's interactive state, grab this dataset and plot it. 
If you have some suggestions re `IDataset` naming, props, or data structure, I'd be happy to hear that. I used an array of arrays for data to keep it more efficient in case we'd like to plot large datasets (on each update dataset needs to be saved in Firestore - not the best for very large datasets, but small and medium are fine).
> Export dataset that can be consumed by the graph interactive

- src/lara-app/components/runtime.tsx
- src/lara-app/hooks/interactive-api.ts
- src/lara-app/utils/generate-dataset.test.tsx
- src/lara-app/utils/generate-dataset.ts
[#175787319]
The main change here is that the dataset is generated immediately after the experiment description is available. This dataset won't have any user data obviously, but it still includes some information (property names) that can be useful for graph interactive to generate empty graphs.
> Send initial, empty dataset to parent (LARA / AP)

- package-lock.json
- package.json
- src/lara-app/components/runtime.tsx
- src/lara-app/hooks/interactive-api.test.ts
- src/lara-app/hooks/interactive-api.ts
[#175787385]
.getFirebaseJwt is part of the .hostFatures now. Init code checks if it's present and the right version, and if not, it just enabled preview mode. That fixes the "waiting to connect to Firestore..." message in LARA authoring preview.
Depends on:
https://github.com/concord-consortium/activity-player/pull/87
> Use preview mode when getFirebaseJwt isn't supported by the host

- src/lara-app/components/runtime.tsx
Manually sets the height of the QR code container so that it is visible when the table is not taller than the QR code container.
> Fix rendering of QR codes [#176699381]

- src/lara-app/components/runtime.tsx
This line of code is commented out in case we want to instead put it behind a query parameter
> Changed to don't show QR code by default in lara app [#177370748]

- package.json
- src/lara-app/hooks/interactive-api.ts
[#177741885]
Vortex was overwriting the existing dataset stored in LARA or AP with an empty one on the initial load. It was causing graphs not to show any data on the page load until the user made any change and the correct dataset was sent to LARA/AP again.
> Make sure that existing dataset in LARA/AP is not overwritten by an empty one

- src/lara-app/hooks/interactive-api.ts
Obfuscated Firebase API key using atob() so that automated key leak detectors are not falsely triggered.
NOTE: the Firebase API key is a public key so this does not leak secrets.
> chore: Obfuscated Firebase API key [PT-187643494]

- src/data/experiments.json
- src/lara-app/utils/generate-dataset.ts
- src/mobile-app/hooks/use-experiments.test.ts
- src/mobile-app/hooks/use-experiments.ts
This adds the foundation of the future support of logging the data from any GDX device as a time series.
NOTE: this does not yet support connecting to any GDX sensor or logging the data as a time series.  Those are in upcoming stories.
NOTE 2: this also temporarily disables the remote experiment update as that would wipe out this new experiment.
> feat: Added "Record Data Trials" experiment [PT-186741111]

- src/data/experiments.json
- src/mobile-app/hooks/use-sensor.test.ts
- src/sensor-demo/index.tsx
- src/sensors/device-sensor.ts
- src/sensors/devices/gdx-sensor.ts
- src/sensors/sensor.ts
- src/shared/components/data-table-field.test.tsx
- src/shared/components/data-table-field.tsx
- src/shared/experiment-types.ts
This allows a secondary way to select sensors instead of just by capabilities.  This will be used by the time series data collection to select any GDX sensor.
> feat: Added experiment filters [PT-187749841]

- src/mobile-app/hooks/use-experiments.ts
This will be reverted later when the new experiments are pushed live.
> fix: Disable previously downloaded experiments for now

- src/lara-app/components/authoring.tsx
- src/lara-app/hooks/interactive-api.ts
This fixes a couple of issues found when testing out authoring:
In authoring mode the authoredState comes in as a string which was causing the authoring preview to show an error that the experiment was not selected.
There was still a reference to the "Save Authored State" button, which I believe came from the S3 authoring version.
> fix: Authored state lookup in authoring mode [PT-187809702]

- src/lara-app/utils/download-csv.test.ts
There were two PRs in parallel with the download PR and the other PR added fields to data used in the download test which then broke after the other PR was merged.
> fix: Download test broken after merge

- src/mobile-app/components/sensor.module.scss
- src/mobile-app/components/sensor.tsx
- src/sensors/devices/gdx-sensor.ts
- src/sensors/mock-sensor.ts
- src/sensors/sensor.ts
- src/shared/components/data-table-field.tsx
- src/shared/components/data-table-sparkgraph.tsx
Also updated the sparkgraphs to use time instead of number of values.
> feat: Added sample rate picker [PT-187809451]

- package-lock.json
- package.json
- src/lara-app/hooks/interactive-api.ts
This was using a *very* old version but shockingly it worked.  This needs to be update to the latest version as the api is going to be updated to enable time series data sets.
> build: Update lara-interactive-api to latest version [PT-187855291]

- src/shared/components/data-table-field.tsx
Disabling the controls breaks data saving as currently implemented.  This may be due to the entire page re-rendering as it is a top level page prop.
This will need to be fixed but it is being disabled for now to enable testing of the rest of the app.
> fix: Disable disable controls for now [PT-187852896]

- src/data/experiments.json
- src/lara-app/utils/download-csv.test.ts
- src/lara-app/utils/download-csv.ts
- src/shared/components/data-table-field.tsx
This allows the experiment author to select a experiment table attribute to use as the timeseries data label in the csv output.
> feat: Add ability to select time series label for csv [PT-187816321]

- src/lara-app/components/app.tsx
- src/lara-app/components/runtime.tsx
- src/lara-app/hooks/interactive-api.ts
- src/shared/components/experiment.tsx
- src/shared/components/photo-or-note-field.tsx
- src/shared/components/section.tsx
This allows for the experiment to be viewed in the class dashboard.  The data is primarily stored in Firebase but the class dashboard does not grant Firebase JWT tokens.
This also updates the lara runtime component to disable inputs when viewing in report mode.
> feat: Save experiment data in interactive state [PT-187809685]

- src/sensors/devices/gdx-sensor.ts
- src/shared/components/data-table-field.tsx
The GDX sensor was not being stopped before restarting recording which caused erroneous values to be displayed when the sample rate was lowered as they would immediately be recorded.
This also updates the spark graph label to start at time 0.  This was evident at the 0.1 sampler rate as the label was immediately showing 10 seconds at the start.
> fix: Stop sensor before restarting recording [PT-187900630]

- src/lara-app/utils/download-csv.test.ts
- src/lara-app/utils/download-csv.ts
This adds the sensor units, if present, to the csv header.
> feat: Add timeseries units to csv output [PT-187816321]

- src/shared/components/data-table-field.tsx
Previously there was a useCallback() wrapper on the stop time series function that depended on the formData but this caused issues with the formData being captured as an empty array at the start of multiple runs where the runs hit their max number of values.
This fix adds a ref to the formData so that the closure is not created.
> fix: Stop series data not saving when max values reached [PT-187949831]

- cypress/integration/branch/experiment.setup.spec.js
[PT-#187949837](https://www.pivotaltracker.com/story/show/187949837)
This pull request addresses the issue described in Pivotal Tracker story [#187949837](https://www.pivotaltracker.com/story/show/187949837). It adds checks to ensure that each time display accurately reflects each row in the table during a Data Trial.
- Added new checks for verifying time displays for each row in the table within a Data Trial.
- During the initial run of this check, the process took 4 hours to complete. However, upon rerunning it this morning, the duration decreased to 19 minutes. This still adds time to our checks.
- Given the increase in run time, we might consider running this Data Trial check locally when needed, instead of including it in the regular automated checks. I'm open to this option if …
> 187949837 add checks for iterative rows

- src/data/experiments-v1.1.0.json
- src/mobile-app/hooks/use-experiments.ts
- src/shared/experiment-types.ts
This change updates the remote experiments file to use a versioned url so that older clients do not download a json file they do not understand (due to the addition of the timeseries data).
> feat: Add v1.1.0 experiments
