package-lock.json
package.json
src/shared/components/bootstrap-form-theme.scss
src/shared/components/experiment.module.scss
src/shared/components/field-template.module.scss
src/shared/components/field-template.tsx
src/shared/components/icon.tsx
src/shared/components/section.tsx
src/shared/components/variables.scss
src/shared/experiment-types.ts
src/shared/index.tsx

[#170820868]
This PR adds:
- custom Icon wrapper around Material UI icons
- custom FieldTemplate that displays icons around form fields and provides other customization
- custom bootstrap theme overwrites
- shows how to use `formUiSchema` to provide icons and placeholders

Style forms, add icons, move towards final Label tab look

---

package-lock.json
package.json
src/index.html
src/mobile-app/components/sensor-value.module.scss
src/mobile-app/components/sensor-value.tsx
src/mobile-app/components/sensor.module.scss
src/mobile-app/components/sensor.tsx
src/mobile-app/hooks/use-sensor.test.ts
src/mobile-app/hooks/use-sensor.ts
src/sensor-demo/index.html
src/sensor-demo/index.scss
src/sensor-demo/index.tsx
src/sensors/bluetooth.d.ts
src/sensors/device-sensor.ts
src/sensors/devices/device.ts
src/sensors/devices/multi-sensor.ts
src/sensors/devices/sensor-tag-2.ts
src/sensors/mock-sensor.ts
src/sensors/sensor.ts
src/shared/utils/log.ts
tslint-build.json
tslint.json
webpack.config.js

- Added mocked sensors [#170567333]
- Add device sensors [#170820923]

Added mock and SensorTag2 sensor

---

__mocks__/svgMock.js
package.json
src/shared/components/data-table-field.test.tsx
src/shared/components/data-table-field.tsx
src/shared/components/experiment.test.tsx
src/shared/components/field-template.test.tsx
src/shared/components/field-template.tsx
src/shared/components/form.tsx
src/shared/components/icon.tsx
src/shared/components/initials.test.tsx
src/shared/components/menu.tsx
src/shared/components/metadata.test.tsx

New test coverage:
Also, I've found some issues in data table field that has been fixed.

Add more tests, fix data table field issues

---

README.md
package.json
src/cordova-wrapper/package.json
src/sensors/device-sensor.ts
src/sensors/devices/sensor-tag-2.ts

Add Bluetooth and Camera access to Cordova-built iOS app.
Added instructions to Readme for others who need to build iOS apps.
Removed one call in the bluetooth connection that was Chrome-specific and was causing errors. 
Noticeable issues that require future work:
Bluetooth connection immediately chooses a sensor without offering a list of nearby devices to choose from.
Camera upload functionality provides little user feedback
Camera upload doesn't seem capture the barcode if you rotate your phone to Landscape after launching in Portrait

iOS Bluetooth

---

.gitignore
package.json
src/lara-app/components/runtime.module.scss
src/lara-app/components/runtime.tsx
src/shared/components/data-table-field.tsx
src/shared/components/experiment.tsx

- If there's no data, the QR code is shown on screen.
- Once data has been uploaded, the QR code is hidden.
- **Not yet working**: the new data (which has been received from Firebase) is not showing up in the table, and I'm not sure why - experimentData is being set with the new data, but it's not triggering the table to repopulate. A reload of the page will show the data.
- The Import button can be clicked again to re-show the QR code.

Table & QR view updates

---

src/mobile-app/components/sensor.module.scss
src/mobile-app/components/sensor.tsx

NOTE: the save button does nothing, its just there to make the user feel good.

Added save button placeholder [#171333030]

---

src/mobile-app/components/app.tsx
src/mobile-app/hooks/use-runs.ts

Also refactored useExperiment hook by extracting a couple of helper functions

Added delete experiment [#170887488]

---

src/cordova-app/index.html
src/cordova-wrapper/config.xml
src/data/experiments.json
src/mobile-app/components/experiment-wrapper.module.scss
src/mobile-app/components/sensor.tsx
src/mobile-app/index.html
src/shared/components/data-table-field.module.scss
src/shared/components/icon.tsx
src/shared/components/variables.scss
src/shared/icons/table_chart-24px.svg
src/shared/index.tsx

- pushed header down so it doesn't overlap statusbar
- removed rescaling of html in mobile app
- fixed opacity of table inputs
- updated collect icon
- removed show plots menu item

UI punchlist before testing [#171514580]

---

src/shared/components/data-table-field.tsx

The data table component was regenerating a new sensor object on re-renders which caused the connection status to be lost.

Fixed disconnect/reconnect on sensors

---

src/data/experiments.json
src/shared/components/data-table-field.tsx

Removes sensors from experiment.
Updated data-table-field.tsx to not show sensor component if there are no sensor fields.

Update Schoolyard investigation [#171539619]

---

package-lock.json
package.json
src/mobile-app/components/experiment-picker-item.module.scss
src/mobile-app/components/experiment-wrapper.module.scss
src/shared/components/data-table-field.module.scss
src/shared/components/data-table-field.tsx
src/shared/components/initials.module.scss
src/shared/components/metadata.module.scss
src/shared/components/section-button.module.scss
src/shared/components/variables.scss
src/shared/index.tsx
src/shared/utils/table-keyboard-nav.test.tsx
src/shared/utils/table-keyboard-nav.ts

[#171094381]
JSDOM has been locked to 15.1.1 because of this issue:
https://github.com/jsdom/jsdom/issues/2586
I extracted this helper to a separate file as it can be useful in another table (not so likely) and data-table-field code can be a bit smaller.

Style manual data columns, add keyboard navigation + specs

---

src/shared/components/data-table-field.test.tsx
src/shared/components/data-table-field.tsx

Don't save table data immediately, ask user first (also while re-recording sensor values)

---

src/mobile-app/components/run-picker.module.scss
src/mobile-app/components/scanner.tsx
src/mobile-app/components/uploader.module.scss
src/mobile-app/components/uploader.tsx
src/mobile-app/icons/scan_overlay.svg
src/shared/components/initials.module.scss
src/shared/components/variables.scss

Camera canvas seems to be a fixed size - I'm not as familiar with the scanner component so haven't been able to dig into this just yet. For now, I have assumed that this is fixed and placed the overlay relative to top-center of the scannable area, but this can easily be adjusted once the canvas is resized accordingly.
I am also unable to test whether the QR scanning functionality still works without being able to get this on a device - I'll try again on xcode later, I am concerned that the overlay might stop the tap-to-scan functionality.

Style upload box to include a scan guide overlay

---

src/mobile-app/components/uploader.module.scss
src/mobile-app/components/uploader.tsx
src/shared/components/photo-or-note-field.tsx

Move the upload camera area down the page a bit and allow room for much longer experiment names

Adjust Uploader styling to allow for much larger run text

---

src/lara-app/components/runtime.tsx
src/mobile-app/components/experiment-wrapper.tsx
src/shared/components/experiment.test.tsx
src/shared/components/photo-or-note-field.tsx
src/shared/experiment-types.ts
src/shared/index.tsx

Also removed camera from Lara app.

Add autosave to Lara app [#171609458]

---

src/mobile-app/components/app.module.scss
src/mobile-app/components/app.tsx
src/mobile-app/components/experiment-picker-item.module.scss
src/mobile-app/components/experiment-picker-item.tsx
src/mobile-app/components/experiment-picker.module.scss
src/mobile-app/components/run-info.tsx
src/mobile-app/components/run-picker.module.scss
src/mobile-app/components/run-picker.tsx
src/mobile-app/components/uploader.tsx
src/shared/components/icon.tsx
src/shared/components/menu.module.scss
src/shared/components/variables.scss

Adjusts the styling to be much closer to the original spec.
[#171332415]

Style experiments list

---

src/shared/components/data-table-field.module.scss
src/shared/components/data-table-field.tsx
src/shared/index.html
src/shared/index.tsx

Ready for review after feedback.

Add cell validation [#170897317]

---

cypress/integration/branch/experiment.setup.spec.js
cypress/integration/branch/sensor.data.spec.js
cypress/supports/elements/ExperimentSetup.js
src/data/experiments.json

- order of sensors matches sensor,
- different field used as subtitle

Changes to match original design

---

src/data/experiments.json
src/mobile-app/components/experiment-wrapper.module.scss
src/mobile-app/components/experiment-wrapper.tsx
src/mobile-app/components/run-info.tsx
src/shared/experiment-types.ts

Click to rename functionality that displays a custom name if one is entered by the user.

Rename experiments [#172091147]

---

functions/src/index.ts
src/lara-app/components/runtime.module.scss
src/lara-app/components/runtime.tsx
src/mobile-app/components/scanner.tsx
src/mobile-app/components/uploader.module.scss
src/mobile-app/components/uploader.tsx
src/shared/api.test.ts
src/shared/api.ts
src/shared/components/photo-or-note-field.tsx

This is a WIP PR as there is some styling issues that still need to be addressed.

Added data transfer by character code [#171903310]

---

cypress/integration/branch/sensor.data.spec.js
src/shared/components/data-table-field.module.scss
src/shared/components/data-table-field.tsx
src/shared/components/icon.tsx
src/shared/components/variables.scss
src/shared/icons/record.svg

Shows an arrow to prompt user to enter new values for rows with no data.

172091930 data capture buttons

---

README.md
package-lock.json
package.json
src/mobile-app/hooks/use-experiments.ts
webpack.config.js

1. Added missing copy of src/data to dist folder
2. Added override of update url
3. Updated semver version to latest.
4. Added update info section to readme.

Fixed remote experiment updates [#171903331]

---

cypress/integration/branch/sensor.data.spec.js
cypress/supports/elements/SensorData.js
src/shared/icons/record.svg

Adjusted the svg to render the "Record" icon, also re-added the tests for the changes to the sensor table.

Cypress fixes and "Record" icon fix

---

src/lara-app/components/runtime.module.scss
src/lara-app/components/runtime.tsx
src/shared/components/data-table-field.tsx
src/shared/experiment-types.ts

The upload button now resides at the top of the runtime component.

Moved upload button to top of Lara app [#172613423]

---

.travis.yml
package-lock.json
package.json
src/lara-app/components/app.module.scss
src/lara-app/components/app.tsx
src/lara-app/components/runtime.module.scss
src/lara-app/components/runtime.tsx
src/lara-app/hooks/interactive-api.ts
src/shared/components/photo-or-note-field.module.scss
src/shared/components/photo-or-note-field.tsx
src/shared/experiment-types.ts

Also added resizing of the interactive in Lara

Add preview mode [#173269377]

---

src/lara-app/components/runtime.module.scss
src/lara-app/components/runtime.tsx
src/lara-app/hooks/interactive-api.ts

This allows for previewing Vortex when the "preview" link is clicked.

Added user preview with warning notice [#173404684]

---

package-lock.json
package.json
src/lara-app/components/runtime.test.tsx
src/lara-app/components/runtime.tsx
src/lara-app/hooks/interactive-api.ts
src/shared/components/data-table-field.tsx
src/shared/utils/handle-special-value.test.ts
src/shared/utils/handle-special-value.ts
webpack.config.cordova-app.js
webpack.config.js

- it adds handling of `<AVG>, <SUM>, <MEAN>`, etc.
- `IDataset` interface has been moved to LARA Interactive API package, so now this package is used here.
- unit tests of dataset generation and function field handling
[#175769743]

Export dataset with pre-calculated function fields

---

package-lock.json
package.json
src/lara-app/utils/generate-dataset.test.tsx
src/lara-app/utils/generate-dataset.ts

[#175876890]
Fixes https://www.pivotaltracker.com/story/show/175876890

Specify different xAxisProp for different experiments

---

src/lara-app/components/runtime.tsx

[#179075154]
Vortex used to generate and save datasets in the `handleSaveData` handler. This was working fine for all the manual edits in the LARA app, but it didn't handle the mobile app upload scenario. The mobile app uploads data directly to Firestore, so the LARA app had no chance to generate and save the dataset. I've moved dataset generation to Firestore#onSnapshot handler. I left a similar call in `handleSaveData`, so the graph synchronization still works in the preview mode.

Generate LARA/AP dataset each time the Firestore data is updated

---

package-lock.json
package.json
src/sensors/device-sensor.ts
src/sensors/devices/device.ts
src/sensors/devices/gdx-sensor.ts
src/typings.d.ts

This adds a generic Vernier GDX sensor class which currently only supports the temperature sensor but is designed to support other sensors as needed.

feat: Add Vernier GDX sensor support [PT-186741116]

---

src/data/experiments.json
src/lara-app/utils/generate-dataset.ts
src/mobile-app/components/sensor.module.scss
src/mobile-app/components/sensor.tsx
src/sensor-demo/index.tsx
src/sensors/device-sensor.ts
src/sensors/devices/device.ts
src/sensors/devices/gdx-sensor.ts
src/sensors/mock-sensor.ts
src/sensors/sensor.ts
src/shared/components/data-table-barchart.tsx
src/shared/components/data-table-field.tsx
src/shared/utils/handle-special-value.ts

NOTE: the start/stop icons are not yet available so they will be added in the next PR.

feat: Added time series data recording [PT-186741110]

---

src/mobile-app/components/sensor.tsx
src/sensors/mock-sensor.ts

Updates the mock sensor poll value to use measurement and unit based on sensor selected.

fix: UI update after mock sensor change [PT-187809478]

---

src/lara-app/components/runtime.tsx

This also fixes the preview warning message showing in the class dashboard.

fix: Show download csv button in class dashboard [PT-187816321]

---

src/shared/components/photo-or-note-field.module.scss
src/shared/components/photo-or-note-field.tsx

- Changed placeholder from "Add a note" to "Add a note and press enter to save"
- Added plus icon over top right of textarea that also adds the note
- Refactored add note code to use comment getter

fix: Update add note UI [PT-187937643]
